version: "3"


services:
  db:
    image: "postgres:latest"
    container_name: stocks-trading
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    networks:
      - db_nw
    privileged: true
    stdin_open: true
    tty: true
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_nw
    depends_on:
      - db
    privileged: true
    stdin_open: true
    tty: true
networks:
  db_nw:
    driver: bridge
volumes:
  dbdata: